# Nexus Comprehensive Demo
# Demonstrates complete data processing pipeline with multiple plugin types

case_info:
  name: "Comprehensive Demo"
  description: "Full pipeline: Generate → Filter → Aggregate → Validate"
  version: "1.0.0"

pipeline:
  # Step 1: Generate synthetic data
  - plugin: "Data Generator"
    config:
      num_rows: 10000
      num_categories: 5
      noise_level: 0.15
      random_seed: 42
      output_data: "data/01_raw_data.csv"

  # Step 2: Filter high-value records
  - plugin: "Data Filter"
    config:
      input_data: "data/01_raw_data.csv"
      output_data: "data/02_filtered.csv"
      column: "value"
      operator: ">"
      threshold: 0.5
      remove_nulls: true

  # Step 3: Aggregate by category
  - plugin: "Data Aggregator"
    config:
      input_data: "data/02_filtered.csv"
      output_data: "data/03_aggregated.csv"
      group_by: "category"
      agg_column: "value"
      agg_function: "mean"

  # Step 4: Validate final output
  - plugin: "Data Validator"
    config:
      input_data: "data/03_aggregated.csv"
      output_report: "reports/validation.json"
      check_nulls: true
      check_duplicates: true
      check_types: true
