# Nexus Video Data Replay Template
# Demonstrates overlaying time-series data onto video frames
# using the new SensorDataManager architecture.

case_info:
  name: "Vehicle Data Replay"
  description: "Extract frames, render speed and ADB target data overlay, compose output video"
  version: "5.5.0" # Version updated to reflect new panel.enabled default

# =============================================================================
# Shared Defaults
# =============================================================================
defaults:
  time_section:
      start_time: "2025-10-27 08:30:10"
      end_time: "2025-10-27 08:30:30"

  timestamps_path: "temp/timeline.csv"
  # Base Textbox configuration to share common styling for all renderers.
  # This is a good use of `defaults` as it's shared by multiple renderers.
  textbox_base_config:
    text_color: [0, 255, 255] # BGR: Yellow (non-default: White)
    outline_color: [0, 0, 0] # Common black outline (non-default: None)
    outline_thickness: 3 # Default: 3

    # PositionConfig parameters (nested)
    position:
      x: "width - 10"
      y: 30
      anchor: 'top_right'

    # FontConfig parameters (nested)
    # font:
    #   face: 0 # Default: cv2.FONT_HERSHEY_SIMPLEX (0)
    #   scale: 0.8 # Default: 0.8
    #   thickness: 1 # Default: 1
    #   line_spacing: 1.5 # Default: 1.5

    # PanelConfig parameters (nested)
    # panel:
    #   enabled: false # Default: false
    #   padding: 10 # Default: 10
    #   bg_color: [40, 40, 40] # Default: (40, 40, 40)
    #   bg_alpha: 0.7 # Default: 0.7
    #   border_color: [100, 100, 100] # Default: (100, 100, 100)
    #   border_thickness: 1 # Default: 1

  # Camera calibration path, used by TargetRenderer
  camera:
    calibration_path: "../../src/nexus/contrib/repro/camera_calibration.json"

# =============================================================================
# Pipeline
# =============================================================================
pipeline:
  - plugin: "Video Splitter"
    # enable: false
    config:
      video_path: "input/*.mp4"
      output_path: "temp/frames"
      frame_pattern: "frame_{:06d}.png"

  - plugin: "Simple Timeline Generator"
    enable: false
    config:
      _extends: "@defaults.time_section"
      fps: 30.0
      timestamps_path: "@defaults.timestamps_path"

  - plugin: "Blank Frame Generator"
    enable: false
    config:
      timestamps_path: "@defaults.timestamps_path"
      output_path: "temp/frames"
      width: 1920
      height: 1080

  # Step 2: Render data onto frames using the new decoupled architecture
  - plugin: "Data Renderer"
    config:
      _extends: "@defaults.time_section"
      frames_dir: "temp/frames"
      output_path: "temp/rendered_frames"
      timestamps_path: "@defaults.timestamps_path"
      frame_pattern: "frame_{:06d}.png"

      # Define all sensor data sources to be managed by SensorDataManager
      sensors:
        - name: "vehicle_speed"
          path: "input/speed.jsonl"
          time_offset_ms: 0
          tolerance_ms: 5000
        - name: "adb_targets"
          path: "input/adb_targets.jsonl"
          time_offset_ms: 0
          tolerance_ms: 50

      # Define how to visualize the sensor data
      renderers:
        # Render frame info (frame ID + timestamp). No sensor needed.
        - class: "nexus.contrib.repro.renderers.FrameInfoRenderer"
          kwargs:
            format: "datetime"
            textbox_config:
              _extends: "@defaults.textbox_base_config"

        # Render vehicle speed by linking to the 'vehicle_speed' sensor.
        # Configuration is now fully inline.
        - class: "nexus.contrib.repro.renderers.SpeedRenderer"
          sensor: "vehicle_speed"
          match_strategy: "forward"
          kwargs:
            # show_timestamp: true # Default: true
            textbox_config:
              _extends: "@defaults.textbox_base_config"
              # TextboxConfig direct parameters
              text_color: [0, 255, 0] # BGR: Green (non-default: White)
              # outline_color: [0, 0, 0] # Inherited from @defaults.textbox_base_config
              # outline_thickness: 3 # Inherited from @defaults.textbox_base_config

              # PositionConfig parameters (nested)
              position:
                x: "width - 30"
                y: 60
                anchor: 'top_right'
              # font:
              #   face: 0 # Default: cv2.FONT_HERSHEY_SIMPLEX (0)
              #   scale: 0.8 # Default: 0.8
              #   thickness: 1 # Default: 1
              #   line_spacing: 1.5 # Default: 1.5

              # PanelConfig parameters (nested)
              # panel:
              #   enabled: false # Default: false
              #   padding: 10 # Default: 10
              #   bg_color: [40, 40, 40] # Default: (40, 40, 40)
              #   bg_alpha: 0.7 # Default: 0.7
              #   border_color: [100, 100, 100] # Default: (100, 100, 100)
              #   border_thickness: 1 # Default: 1

        # Render 3D target detections by linking to the 'adb_targets' sensor.
        # Configuration is now fully inline.
        - class: "nexus.contrib.repro.renderers.TargetRenderer"
          sensor: "adb_targets"
          match_strategy: "nearest"
          kwargs:
            bounds_display_format: "angle"
            calibration_path: "@defaults.camera.calibration_path"
            box_color: [0, 255, 0] # Default: [0,255,0] (from TextboxConfig default if not overridden)
            box_thickness: 2 # Default: 1 (from FontConfig default if not overridden)
            show_box_label: true # Default: true
            # show_timestamp: true # Default: true
            textbox_config:
              _extends: "@defaults.textbox_base_config"
              # TextboxConfig direct parameters
              text_color: [0, 255, 255] # BGR: Yellow text (non-default: White)
              # outline_color: [0, 0, 0] # Inherited from @defaults.textbox_base_config
              # outline_thickness: 3 # Inherited from @defaults.textbox_base_config

              # PositionConfig parameters (nested)
              position:
                x: "width - 10"
                y: "height - 10"
                anchor: 'bottom_right'
              # FontConfig parameters (nested)
              font:
                scale: 0.8 # Default: 0.8
                # face: 0 # Default: cv2.FONT_HERSHEY_SIMPLEX (0)
                # thickness: 1 # Default: 1
                # line_spacing: 1.5 # Default: 1.5

              # PanelConfig parameters (nested)
              panel:
                enabled: true # Non-default: false
                # padding: 10 # Default: 10
                # bg_color: [40, 40, 40] # Default: (40, 40, 40)
                # bg_alpha: 0.7 # Default: 0.7
                # border_color: [100, 100, 100] # Default: (100, 100, 100)
                # border_thickness: 1 # Default: 1

  # Step 3: Compose rendered frames back to video
  - plugin: "Video Composer"
    # enable: false
    config:
      frames_dir: "temp/rendered_frames"
      output_path: "output/repro.mp4"
      fps: 30.0
      frame_pattern: "frame_{:06d}.png"