# Nexus Video Data Replay Template
# Demonstrates overlaying time-series data onto video frames
# with shared configuration using @defaults references

case_info:
  name: "Vehicle Data Replay"
  description: "Extract frames, render speed and ADB target data overlay, compose output video"
  version: "4.0.0"

# =============================================================================
# Shared Defaults
# =============================================================================
# Define reusable configuration blocks here
# Reference them in pipeline using @defaults.xxx syntax

defaults:
  # Common renderer settings
  renderer_base:
    time_offset_ms: 0
    tolerance_ms: 50.0

  # Speed renderer configuration
  speed_renderer:
    position: [30, 60]
    tolerance_ms: 5000.0  # Forward matching: hold speed up to 5s
    font_scale: 1.2
    color: [0, 255, 0]    # Green
    thickness: 3

  # Target renderer configuration
  target_renderer:
    tolerance_ms: 50.0    # Nearest matching: within 50ms
    box_color: [0, 255, 0]  # Green boxes
    box_thickness: 2
    show_panel: true

  # Camera calibration path
  camera:
    calibration_path: "../../src/nexus/contrib/repro/camera_calibration.json"

# =============================================================================
# Pipeline
# =============================================================================

pipeline:
  # Step 1: Extract frames from video
  - plugin: "Video Splitter"
    config:
      video_path: "input/synthetic_driving.mp4"
      output_dir: "temp/frames"
      frame_pattern: "frame_{:06d}.png"

  # Step 2: Render data onto frames using modular renderers
  - plugin: "Data Renderer"
    config:
      # Time range control
      start_time: "2025-10-27 08:30:10"
      end_time: "2025-10-27 08:30:30"
      frames_dir: "temp/frames"
      output_dir: "temp/rendered_frames"
      frame_pattern: "frame_{:06d}.png"
      timestamps_path: "input/vehicle_timeline.csv"  # Real frame acquisition timestamps
      show_frame_info: true

      # Renderers with shared configuration
      renderers:
        # Render vehicle speed using shared config
        - class: "nexus.contrib.repro.renderers.SpeedRenderer"
          kwargs:
            _extends: "@defaults.speed_renderer"  # Inherit speed_renderer defaults
            data_path: "input/speed.jsonl"        # Add data_path
            time_offset_ms: 0                     # Can override defaults

        # Render 3D target detections using shared config
        - class: "nexus.contrib.repro.renderers.TargetRenderer"
          kwargs:
            _extends: "@defaults.target_renderer"                # Inherit target_renderer defaults
            data_path: "input/adb_targets.jsonl"
            calibration_path: "@defaults.camera.calibration_path"  # Reference nested value
            time_offset_ms: 0
            show_panel: true

  # Step 3: Compose rendered frames back to video
  - plugin: "Video Composer"
    config:
      frames_dir: "temp/rendered_frames"
      output_path: "output/vehicle_replay.mp4"
      fps: 30.0
      frame_pattern: "frame_{:06d}.png"
      codec: "mp4v"

# Architecture Notes:
#
# 1. Modular Renderers (Class-Based):
#    - Each renderer handles ONE data type
#    - Use full qualified class names in config
#    - SpeedRenderer: Vehicle speed with forward matching
#    - TargetRenderer: 3D object detection with projection
#
# 2. Easy to Extend:
#    - Add new data type: Create a renderer class
#    - Inherit from BaseDataRenderer
#    - Use full class name in renderers list
#    - Example: "your.module.path.GPSRenderer"
#
# 3. Matching Strategies:
#    - Forward: Use most recent data ≤ timestamp (good for speed, GPS)
#    - Nearest: Use closest data point (good for high-freq like targets)
#    - Backward: Use earliest data ≥ timestamp (for predictive data)
#
# 4. Data Flow:
#    Video → Frames → [Renderer 1] → [Renderer 2] → ... → Rendered Frames → Video
#    Each renderer applies its visualization sequentially
#
# Example: Adding Custom Renderer
#
# # 1. Define renderer class:
# from nexus.contrib.repro.renderers import BaseDataRenderer
#
# class GPSRenderer(BaseDataRenderer):
#     def __init__(self, data_path, position=(20, 100), **kwargs):
#         super().__init__(data_path, **kwargs)
#         self.position = position
#
#     def render(self, frame, timestamp_ms):
#         matched = self.match_data(timestamp_ms)
#         if matched:
#             # Draw GPS data on frame
#             pass
#         return frame
#
# # 2. Add to config using full class name:
# renderers:
#   - class: "nexus.contrib.repro.renderers.SpeedRenderer"
#     kwargs: { ... }
#
#   - class: "nexus.contrib.repro.renderers.TargetRenderer"
#     kwargs: { ... }
#
#   - class: "your.module.path.GPSRenderer"  # Your custom renderer
#     kwargs:
#       data_path: "input/gps.jsonl"
#       position: [20, 100]
#       tolerance_ms: 1000
#

