# Nexus Video Data Replay Template
# Demonstrates overlaying time-series data onto video frames
# with shared configuration using @defaults references

case_info:
  name: "Vehicle Data Replay"
  description: "Extract frames, render speed and ADB target data overlay, compose output video"
  version: "4.1.0"

# =============================================================================
# Shared Defaults
# =============================================================================
# Define reusable configuration blocks here
# Reference them in pipeline using @defaults.xxx syntax

defaults:
  # Common renderer settings
  renderer_base:
    time_offset_ms: 0
    tolerance_ms: 50.0

  # --- New Unified Text Style and Position Defaults ---

  # Base text style for all renderers
  base_text_style: &base_text_style
    font_scale: 0.6
    thickness: 1
    color: [0, 255, 255] # BGR: Yellow

  # Style for the Speed Renderer
  speed_style: &speed_style
    <<: *base_text_style      # Inherit base style
    font_scale: 1.2
    thickness: 3
    color: [0, 255, 0]       # BGR: Green
    position:
      anchor: top_left       # Anchor the text's top-left corner
      coords: [30, 60]       # at absolute pixel (30, 60)

  # Style for the Target Info List Renderer
  target_info_style: &target_info_style
    <<: *base_text_style      # Inherit base style
    position:
      anchor: bottom_left    # Anchor the text block's bottom-left corner
      coords: [10, -10]      # at 10px from left, 10px from bottom of the frame

  # Non-style configuration for TargetRenderer
  target_renderer_config: &target_renderer_config
    tolerance_ms: 50.0
    box_color: [0, 255, 0]
    box_thickness: 2

  # Camera calibration path
  camera:
    calibration_path: "../../src/nexus/contrib/repro/camera_calibration.json"

# =============================================================================
# Pipeline
# =============================================================================

pipeline:
  # Step 1: Extract frames from video
  - plugin: "Video Splitter"
    config:
      video_path: "input/*.mp4"
      output_path: "temp/frames"
      frame_pattern: "frame_{:06d}.png"

  # Step 2: Render data onto frames using modular renderers
  - plugin: "Data Renderer"
    config:
      start_time: "2025-10-27 08:30:10"
      end_time: "2025-10-27 08:30:30"
      frames_dir: "temp/frames"
      output_path: "temp/rendered_frames"
      timestamps_path: "input/vehicle_timeline.csv"

      renderers:
        # Render frame info (frame ID + timestamp)
        - class: "nexus.contrib.repro.renderers.FrameInfoRenderer"
          kwargs:
            format: "datetime"
            style:
              <<: *base_text_style
              position:
                anchor: top_left
                coords: [10, 30]

        # Render vehicle speed using shared config
        - class: "nexus.contrib.repro.renderers.SpeedRenderer"
          kwargs:
            data_path: "input/speed.jsonl"
            tolerance_ms: 5000.0  # Hold speed up to 5s
            style: *speed_style     # Use the shared speed style

        # Render 3D target detections using shared config
        - class: "nexus.contrib.repro.renderers.TargetRenderer"
          kwargs:
            <<: *target_renderer_config # Inherit non-style config
            data_path: "input/adb_targets.jsonl"
            calibration_path: "@defaults.camera.calibration_path"
            style: *target_info_style # Use the shared target info style

  # Step 3: Compose rendered frames back to video
  - plugin: "Video Composer"
    config:
      frames_dir: "temp/rendered_frames"
      output_path: "output/vehicle_replay.mp4"
      fps: 30.0
      frame_pattern: "frame_{:06d}.png"
      codec: "mp4v"

# Architecture Notes:
#
# 1. New Position and Style Configuration:
#    - Text rendering is now controlled by a 'style' object.
#    - The 'position' object inside 'style' defines placement.
#
#    style:
#      position:
#        anchor: "top_left"  # Anchor point on the text box
#        coords: [10, 30]    # [x, y] coordinates for the anchor
#        is_relative: false  # false=pixels, true=percentage (0.0-1.0)
#      color: [0, 255, 255]
#      font_scale: 0.6
#      thickness: 1
#
#    Anchor options:
#      - top_left, top_center, top_right
#      - center_left, center, center_right
#      - bottom_left, bottom_center, bottom_right
#
#    Coordinate shorthand:
#    - Negative coordinates are relative to the far edge (width/height).
#      e.g., coords: [10, -10] with anchor: bottom_left places the text
#      10px from the left and 10px from the bottom.
#    - A simple list `position: [10, 30]` is a shorthand for
#      `anchor: top_left`, `coords: [10, 30]`.
#
# 2. Reusability with YAML Anchors:
#    - Use '&' to define a reusable block (e.g., &base_text_style).
#    - Use '*' to reference a block (e.g., *base_text_style).
#    - Use '<<:' to merge blocks.
#
#    Example:
#      defaults:
#        base_style: &base
#          font_scale: 0.6
#        speed_style: &speed
#          <<: *base
#          color: [0, 255, 0]
#      ...
#      renderers:
#        - class: ...
#          kwargs:
#            style: *speed  # font_scale is 0.6, color is green