# Nexus Data Generation Template for Vehicle Data Replay
# Generates synthetic video, timeline, speed, and ADB target data for testing

case_info:
  name: "Vehicle Data Generation"
  description: "Generate synthetic video and data (timeline, speed, ADB targets)"
  version: "3.0.0"

pipeline:
  # Step 0: Generate synthetic driving video (NEW!)
  # Creates a 1-minute 1920x1080 video simulating forward driving
  - plugin: "Synthetic Video Generator"
    config:
      output_path: "input/synthetic_driving.mp4"
      duration_s: 60.0                    # 1 minute video
      fps: 30.0                           # 30 FPS
      width: 1920                         # Full HD width
      height: 1080                        # Full HD height
      speed_kmh: 60.0                     # Simulated vehicle speed
      random_seed: 42                     # For reproducibility

  # Step 1: Generate timeline with realistic jitter
  # Automatically extracts FPS and frame count from video
  - plugin: "Timeline Generator"
    config:
      video_path: "input/synthetic_driving.mp4"    # Video file to analyze
      start_time: "2025-10-27 08:30:00"  # Human-readable time format
      jitter_ms: 2                        # ±2ms random jitter (integer)
      output_csv: "input/vehicle_timeline.csv"
      random_seed: 42                     # For reproducibility

  # Step 2: Generate event-driven speed data
  # Speed data is INDEPENDENT - can be longer or shorter than video
  # Only records when speed changes or every 5 seconds minimum
  - plugin: "Speed Data Generator"
    config:
      # start_time automatically inherited from Timeline Generator
      duration_s: 60.0                    # Generate 60s of speed data (matches video)
      max_interval_s: 5.0                 # Send at least every 5 seconds
      speed_change_threshold: 2.0         # Record if speed changes by 2+ km/h
      output_jsonl: "input/speed.jsonl"
      random_seed: 42
      use_default_profile: true           # Realistic driving: accelerate, cruise, decelerate

  # Step 3: Generate ADB target data (20Hz with timing jitter)
  # Simulates adaptive driving beam system detecting vehicles/pedestrians
  # Data is INDEPENDENT - generated at 20Hz regardless of video frame rate
  - plugin: "ADB Target Generator"
    config:
      # start_time automatically inherited from Timeline Generator
      duration_s: 60.0                    # Generate 60s of target data (matches video)
      frequency_hz: 20.0                  # Fixed 20Hz data rate
      timing_jitter_ms: 2                 # ±2ms reception timing error (integer)
      num_targets: 3                      # 2-3 concurrent targets
      ego_speed_kmh: 60.0                 # Our vehicle speed
      output_jsonl: "input/adb_targets.jsonl"
      random_seed: 42

# Configuration Notes:
#
# 0. Synthetic Video Generation (NEW!):
#    - Generates 1920x1080 @ 30 FPS video
#    - Simulates forward driving with lane markings
#    - Perspective projection for realistic view
#    - No need for external video file
#
# 1. Video Input:
#    - Timeline Generator extracts FPS and duration automatically
#    - Example: 30 FPS, 1800 frames = 60 seconds
#
# 2. Time Format:
#    - Use human-readable: "2025-10-27 08:30:00"
#    - Automatically converted to Unix timestamp (ms)
#
# 3. Data Generation:
#    - All data now matches video duration (60s)
#    - Speed and ADB data synchronized with video timeline
#
# 4. Data Frequencies:
#    - Timeline: Matches video FPS (30 FPS)
#    - Speed: Event-driven (change + 5s minimum)
#    - ADB: Fixed 20Hz with ±2ms jitter
#
# Expected Output Files:
# - input/synthetic_driving.mp4: Synthetic driving video (1920x1080 @ 30 FPS, 60s)
# - input/vehicle_timeline.csv: Frame timestamps with ±1.5ms jitter
# - input/speed.jsonl: Event-driven speed data
# - input/adb_targets.jsonl: 20Hz ADB target detections
#
# Usage:
#   nexus run -c repro -t repro_datagen
#
# Data Format Examples:
#
# vehicle_timeline.csv:
#   frame_index,timestamp_ms
#   0,1730019000000.0
#   1,1730019000034.8
#   2,1730019000067.1
#
# speed.jsonl (event-driven):
#   {"timestamp_ms": 1730019000000.0, "speed": 0.0}
#   {"timestamp_ms": 1730019002150.5, "speed": 12.3}
#   {"timestamp_ms": 1730019007890.2, "speed": 25.8}
#
# adb_targets.jsonl (20Hz, edge angles format):
#   {"timestamp_ms": 1730019000000.0, "targets": [
#     {
#       "id": 1,
#       "type": "car",
#       "distance_m": 45.2,
#       "angle_left": 1.8,
#       "angle_right": 2.8,
#       "angle_top": -0.3,
#       "angle_bottom": -0.7
#     }
#   ]}
#   {"timestamp_ms": 1730019000052.3, "targets": [
#     {
#       "id": 1,
#       "type": "car",
#       "distance_m": 44.8,
#       "angle_left": 1.9,
#       "angle_right": 2.9,
#       "angle_top": -0.3,
#       "angle_bottom": -0.7
#     }
#   ]}


