# Nexus Video Data Replay Template
# Demonstrates overlaying time-series data onto video frames
# with shared configuration using @defaults references

case_info:
  name: "Vehicle Data Replay"
  description: "Extract frames, render speed and ADB target data overlay, compose output video"
  version: "4.0.0"

# =============================================================================
# Shared Defaults
# =============================================================================
# Define reusable configuration blocks here
# Reference them in pipeline using @defaults.xxx syntax

defaults:
  # Common renderer settings
  renderer_base:
    time_offset_ms: 0
    tolerance_ms: 50.0

  # Speed renderer configuration
  speed_renderer:
    position: [30, 60]
    tolerance_ms: 5000.0  # Forward matching: hold speed up to 5s
    font_scale: 1.2
    color: [0, 255, 0]    # BGR: Green
    thickness: 3

  # Target renderer configuration
  target_renderer:
    tolerance_ms: 50.0    # Nearest matching: within 50ms
    box_color: [0, 255, 0]  # BGR: Green boxes
    box_thickness: 2
    text_color: [0, 255, 255]  # BGR: Yellow text
    font_scale: 0.6
    text_thickness: 1
    text_position: null   # Auto: [10, frame_height-10] (bottom-left corner)
                          # Custom: [x, y] where y is from bottom
    show_box_label: false # Show ID label above each box (default: false)
    show_panel: false     # Show detailed info panel (default: false)

  # Camera calibration path
  camera:
    calibration_path: "../../src/nexus/contrib/repro/camera_calibration.json"

# =============================================================================
# Pipeline
# =============================================================================

pipeline:
  # Step 1: Extract frames from video
  - plugin: "Video Splitter"
    # enable: true  # Default, no need to specify
    config:
      video_path: "input/*.mp4"
      output_path: "temp/frames"
      frame_pattern: "frame_{:06d}.png"

  # Step 2: Render data onto frames using modular renderers
  - plugin: "Data Renderer"
    config:
      # Time range control
      start_time: "2025-10-27 08:30:10"
      end_time: "2025-10-27 08:30:30"
      frames_dir: "temp/frames"
      output_path: "temp/rendered_frames"
      frame_pattern: "frame_{:06d}.png"
      timestamps_path: "input/vehicle_timeline.csv"  # Real frame acquisition timestamps
      show_frame_info: true

      # Renderers with shared configuration
      # Each renderer supports 'enable' field to control execution (default: true)
      renderers:
        # Render vehicle speed using shared config
        - class: "nexus.contrib.repro.renderers.SpeedRenderer"
          # enable: true  # Default, can be omitted
          kwargs:
            _extends: "@defaults.speed_renderer"  # Inherit speed_renderer defaults
            data_path: "input/speed.jsonl"        # Add data_path
            time_offset_ms: 0                     # Can override defaults

        # Render 3D target detections using shared config
        - class: "nexus.contrib.repro.renderers.TargetRenderer"
          enable: true  # Explicitly enabled (optional, as true is default)
          kwargs:
            _extends: "@defaults.target_renderer"                # Inherit target_renderer defaults
            data_path: "input/adb_targets.jsonl"
            calibration_path: "@defaults.camera.calibration_path"  # Reference nested value
            time_offset_ms: 0
            # text_position: [15, 1070]  # Optional: Custom position (default: auto bottom-left)
            # show_box_label: false  # Show ID above each box (default: false)
            # show_panel: false  # Show detailed panel (default: false)

  # Step 3: Compose rendered frames back to video
  - plugin: "Video Composer"
    config:
      frames_dir: "temp/rendered_frames"
      output_path: "output/vehicle_replay.mp4"
      fps: 30.0
      frame_pattern: "frame_{:06d}.png"
      codec: "mp4v"

      # Option 1: Use time range (preferred, requires frame_timestamps.csv)
      # start_time: "2025-10-27 08:30:10"
      # end_time: "2025-10-27 08:30:30"
      # timestamps_path: "input/vehicle_timeline.csv"  # Optional, auto-detected from frames_dir

      # Option 2: Use frame index range
      # start_frame: 0      # First frame (0-based)
      # end_frame: 900      # Last frame (None for all)

      # Note: If both time range and frame index are specified, time range takes priority

# Architecture Notes:
#
# 1. Modular Renderers (Class-Based):
#    - Each renderer handles ONE data type
#    - Use full qualified class names in config
#    - SpeedRenderer: Vehicle speed with forward matching
#    - TargetRenderer: 3D object detection with projection
#
# 2. Text Rendering Configuration:
#    All renderers support customizable text appearance:
#    - position: [x, y] - Text position (SpeedRenderer)
#    - font_scale: float - Font size multiplier (e.g., 1.2, 0.6)
#    - color / text_color: [B, G, R] - Text color in BGR format
#      Examples: [0, 255, 0] = Green, [0, 255, 255] = Yellow, [255, 0, 0] = Blue
#    - thickness / text_thickness: int - Text line thickness
#    - Text uses black outline automatically for better visibility
#
#    TargetRenderer special features:
#    - text_position: [x, y] - Bottom-left anchor for target info list
#      Default: [10, frame_height-10] (auto-calculated)
#      Custom: [15, 1070] for 1080p video
#    - Target list stacks UPWARD when there are many targets
#    - Each target shows as: "ID:1 car 45.2m"
#    - show_box_label: Show ID above each box (default: false)
#    - show_panel: Show detailed panel (default: false)
#
#    Example - Multiple speed displays with different colors:
#      - class: "nexus.contrib.repro.renderers.SpeedRenderer"
#        kwargs:
#          data_path: "input/speed_raw.jsonl"
#          position: [30, 60]
#          font_scale: 1.2
#          color: [0, 255, 0]    # Green
#          thickness: 3
#
#      - class: "nexus.contrib.repro.renderers.SpeedRenderer"
#        kwargs:
#          data_path: "input/speed_smooth.jsonl"
#          position: [30, 120]
#          font_scale: 1.0
#          color: [0, 255, 255]  # Yellow
#          thickness: 2
#
#    Example - Custom target info position:
#      - class: "nexus.contrib.repro.renderers.TargetRenderer"
#        kwargs:
#          data_path: "input/targets.jsonl"
#          calibration_path: "calib.json"
#          text_position: [15, 1070]  # 10px from bottom on 1080p
#          text_color: [0, 255, 255]  # Yellow
#          font_scale: 0.6
#
# 3. Easy to Extend:
#    - Add new data type: Create a renderer class
#    - Inherit from BaseDataRenderer
#    - Use full class name in renderers list
#    - Example: "your.module.path.GPSRenderer"
#
# 4. Matching Strategies:
#    - Forward: Use most recent data ≤ timestamp (good for speed, GPS)
#    - Nearest: Use closest data point (good for high-freq like targets)
#    - Backward: Use earliest data ≥ timestamp (for predictive data)
#
# 5. Data Flow:
#    Video → Frames → [Renderer 1] → [Renderer 2] → ... → Rendered Frames → Video
#    Each renderer applies its visualization sequentially
#
# 6. Enable/Disable Steps:
#    Use 'enable' field to control step execution:
#    - enable: true  (default, executes the step)
#    - enable: false (skips the step)
#
#    Example - Skip video composition:
#      - plugin: "Video Composer"
#        enable: false
#        config: { ... }
#
#    When disabled, log shows: "Skipping disabled plugin (step N): Plugin Name"
#
# 7. Enable/Disable Renderers:
#    Each renderer also supports 'enable' field:
#    - enable: true  (default, executes the renderer)
#    - enable: false (skips the renderer)
#
#    Example - Skip target rendering:
#      - class: "nexus.contrib.repro.renderers.TargetRenderer"
#        enable: false
#        kwargs: { ... }
#
#    When disabled, log shows: "Skipping disabled renderer (#N): ClassName"
#
# Example: Adding Custom Renderer
#
# # 1. Define renderer class:
# from nexus.contrib.repro.renderers import BaseDataRenderer
#
# class GPSRenderer(BaseDataRenderer):
#     def __init__(self, data_path, position=(20, 100), **kwargs):
#         super().__init__(data_path, **kwargs)
#         self.position = position
#
#     def render(self, frame, timestamp_ms):
#         matched = self.match_data(timestamp_ms)
#         if matched:
#             # Draw GPS data on frame
#             pass
#         return frame
#
# # 2. Add to config using full class name:
# renderers:
#   - class: "nexus.contrib.repro.renderers.SpeedRenderer"
#     kwargs: { ... }
#
#   - class: "nexus.contrib.repro.renderers.TargetRenderer"
#     kwargs: { ... }
#
#   - class: "your.module.path.GPSRenderer"  # Your custom renderer
#     kwargs:
#       data_path: "input/gps.jsonl"
#       position: [20, 100]
#       tolerance_ms: 1000
#

