# Nexus Video Data Replay Template
# Demonstrates overlaying time-series data onto video frames
# with shared configuration using @defaults references

case_info:
  name: "Vehicle Data Replay"
  description: "Extract frames, render speed and ADB target data overlay, compose output video"
  version: "4.1.0" # Version updated to reflect config changes

# =============================================================================
# Shared Defaults
# =============================================================================
defaults:
  # Common renderer settings
  renderer_base:
    time_offset_ms: 0
    tolerance_ms: 50.0

  # Base Textbox configuration to share common styling
  textbox_base_config:
    # font.face: 0 matches default (cv2.FONT_HERSHEY_SIMPLEX)
    # font.line_spacing: 1.5 matches default
    outline_color: [0, 0, 0] # Common black outline (non-default)
    # outline_thickness: 3 matches default

  # Speed renderer configuration
  speed_renderer:
    # Textbox settings are now nested under textbox_config
    textbox_config:
      _extends: "@defaults.textbox_base_config" # Inherit common textbox settings
      position:
        x: "width - 30" 
        y: 60 
        anchor: 'top_right'
      font:
        # scale: 0.8 
        # thickness: 1 
      panel:
        enabled: false 
      text_color: [0, 255, 0] # BGR: Green (non-default)

  # Target renderer configuration
  target_renderer:
    tolerance_ms: 50.0
    box_color: [0, 255, 0]
    box_thickness: 2
    show_box_label: true # Show ID label above each box (default: false)
    # Textbox settings are now nested under textbox_config
    textbox_config:
      _extends: "@defaults.textbox_base_config" # Inherit common textbox settings
      position:
        x: "width - 10"
        y: "height - 10" 
        anchor: 'bottom_right' 
      font:
        scale: 0.8 
        # thickness: 1 matches default
      # panel.enabled: true matches default
      text_color: [0, 255, 255] # BGR: Yellow text (non-default)

  # Camera calibration path
  camera:
    calibration_path: "../../src/nexus/contrib/repro/camera_calibration.json"

# =============================================================================
# Pipeline
# =============================================================================
pipeline:
  # Step 1: Extract frames from video
  - plugin: "Video Splitter"
    enable: false
    config:
      video_path: "input/*.mp4"
      output_path: "temp/frames"
      frame_pattern: "frame_{:06d}.png" # Re-added

  # Step 2: Render data onto frames using modular renderers
  - plugin: "Data Renderer"
    config:
      start_time: "2025-10-27 08:30:10"
      end_time: "2025-10-27 08:30:30"
      frames_dir: "temp/frames"
      output_path: "temp/rendered_frames"
      timestamps_path: "input/vehicle_timeline.csv"
      frame_pattern: "frame_{:06d}.png" # Re-added

      renderers:
        # Render frame info (frame ID + timestamp) in top-left corner
        - class: "nexus.contrib.repro.renderers.FrameInfoRenderer"
          kwargs:
            format: "datetime" # "compact", "datetime", or "detailed"
            textbox_config:
              _extends: "@defaults.textbox_base_config" # Inherit common textbox settings
              position:
                x: "width - 10"
                y: 30 
                anchor: 'top_right'
              font:
                # scale: 0.8 
                # thickness: 1 matches default
              panel:
                enabled: false 
              text_color: [0, 255, 255] # BGR: Yellow (non-default)

        # Render vehicle speed using shared config
        - class: "nexus.contrib.repro.renderers.SpeedRenderer"
          kwargs:
            _extends: "@defaults.speed_renderer" # Inherit speed_renderer defaults
            data_path: "input/speed.jsonl"
            time_offset_ms: 0

        # Render 3D target detections using shared config
        - class: "nexus.contrib.repro.renderers.TargetRenderer"
          kwargs:
            _extends: "@defaults.target_renderer" # Inherit target_renderer defaults
            data_path: "input/adb_targets.jsonl"
            calibration_path: "@defaults.camera.calibration_path"
            time_offset_ms: 0

  # Step 3: Compose rendered frames back to video
  - plugin: "Video Composer"
    config:
      frames_dir: "temp/rendered_frames"
      output_path: "output/vehicle_replay.mp4"
      fps: 30.0
      frame_pattern: "frame_{:06d}.png" # Re-added

# Architecture Notes have been simplified as the new TextboxConfig is self-documenting.
#
# - Text Rendering: All text rendering is now controlled by a 'textbox_config' block
#   which maps directly to the TextboxConfig dataclass in utils_text.py.
#   This includes position, font, panel, and color settings.
#
# - To customize a renderer's text, modify its 'textbox_config' section.