# Analytics Pipeline Template
# For data analysis and reporting workflows
#
# Usage:
#   nexus run --case my-case --template analytics

case_info:
  name: "Data Analytics Pipeline"
  description: "Comprehensive data analysis with aggregation and reporting"
  template: "analytics"
  version: "1.0.0"

pipeline:
  # Data Generation
  - plugin: "Sample Data Generator"
    config:
      # I/O configuration
      output_data: "data/raw_sales.csv"

      # Behavior configuration
      dataset_type: "sales"
      size: "large"

  # Data Cleaning
  - plugin: "Data Cleaner"
    config:
      # I/O configuration
      input_data: "data/raw_sales.csv"
      output_data: "data/cleaned_sales.csv"

      # Behavior configuration
      remove_outliers: true
      outlier_threshold: 2.5
      fill_missing: true
      missing_strategy: "median"

  # Feature Engineering
  - plugin: "Data Transformer"
    config:
      # I/O configuration
      input_data: "data/cleaned_sales.csv"
      output_data: "data/featured_sales.parquet"

      # Behavior configuration
      normalize_columns: ["unit_price", "quantity"]
      create_derived_features: true

  # Data Aggregation
  - plugin: "Data Aggregator"
    config:
      # I/O configuration
      input_data: "data/featured_sales.parquet"
      output_data: "reports/product_summary.csv"

      # Behavior configuration
      group_by_column: "product"
      aggregation_method: "mean"

  # Final Quality Check
  - plugin: "Data Quality Checker"
    config:
      # I/O configuration
      input_data: "reports/product_summary.csv"
      output_report: "reports/analytics_quality.json"

      # Behavior configuration
      check_duplicates: true
      check_outliers: false
