# Data Quality Assessment Template
# Focused on comprehensive data quality analysis and validation
#
# Usage:
#   nexus run --case my-case --template data-quality

case_info:
  name: "Data Quality Assessment"
  description: "Comprehensive data quality analysis and validation pipeline"
  template: "data-quality"
  version: "1.0.0"

pipeline:
  # Data Generation for Testing
  - plugin: "Sample Data Generator"
    config:
      # I/O configuration
      output_data: "data/source_data.csv"

      # Behavior configuration
      dataset_type: "customers"
      size: "medium"

  # Comprehensive Validation
  - plugin: "Data Validator"
    config:
      # I/O configuration
      input_data: "data/source_data.csv"
      output_report: "reports/validation_detailed.json"

      # Behavior configuration
      required_columns: ["customer_id", "first_name", "last_name", "age"]
      min_rows: 500
      max_null_percentage: 0.02

  # Quality Assessment
  - plugin: "Data Quality Checker"
    config:
      # I/O configuration
      input_data: "data/source_data.csv"
      output_report: "reports/quality_comprehensive.json"

      # Behavior configuration
      check_duplicates: true
      check_data_types: true
      check_outliers: true
      check_consistency: true
      outlier_threshold: 2.0
