# ETL Pipeline Template
# Complete Extract-Transform-Load pipeline for data processing

case_info:
  name: "ETL Data Pipeline"
  description: "Complete ETL pipeline with comprehensive data processing"
  template: "etl-pipeline"
  version: "1.0.0"

pipeline:
  # Extract Phase
  - plugin: "Data Generator"
    config:
      num_rows: 5000
      num_categories: 5
      noise_level: 0.15
    outputs:
      - name: "raw_data"

  # Initial Validation
  - plugin: "Data Validator"
    config:
      required_columns: ["id", "category", "value", "score"]
      min_rows: 1000
      max_null_percentage: 0.05
    outputs:
      - name: "extraction_validation"

  # Transform Phase
  - plugin: "Data Cleaner"
    config:
      remove_outliers: true
      outlier_threshold: 3.0
      fill_missing: true
      missing_strategy: "mean"
    outputs:
      - name: "cleaned_data"

  - plugin: "Data Transformer"
    config:
      normalize_columns: ["value", "score"]
      log_transform_columns: ["value"]
      create_derived_features: true
    outputs:
      - name: "transformed_data"

  # Load Phase Validation
  - plugin: "Data Quality Checker"
    config:
      check_duplicates: true
      check_data_types: true
      check_outliers: true
      outlier_threshold: 2.5
    outputs:
      - name: "quality_report"

data_sources:
  raw_data:
    handler: "csv"
    path: "data/01_raw/extract_data.csv"
    must_exist: false

  cleaned_data:
    handler: "csv"
    path: "data/02_intermediate/cleaned_data.csv"
    must_exist: false

  transformed_data:
    handler: "parquet"
    path: "data/03_processed/transformed_data.parquet"
    must_exist: false
    handler_args:
      compression: "snappy"

  extraction_validation:
    handler: "json"
    path: "reports/01_extraction_validation.json"
    must_exist: false

  quality_report:
    handler: "json"
    path: "reports/02_quality_assessment.json"
    must_exist: false

plugins:
  "Data Generator":
    random_seed: 123

  "Data Transformer":
    normalize_columns: ["value", "score"]
    create_derived_features: true
