# ETL Pipeline Template
# Complete Extract-Transform-Load pipeline for data processing
#
# Usage:
#   nexus run --case my-case --template etl-pipeline

case_info:
  name: "ETL Data Pipeline"
  description: "Complete ETL pipeline with comprehensive data processing"
  template: "etl-pipeline"
  version: "1.0.0"

pipeline:
  # Extract Phase - Generate synthetic data
  - plugin: "Data Generator"
    config:
      # I/O configuration
      output_data: "data/01_raw/extract_data.csv"

      # Behavior configuration
      num_rows: 5000
      num_categories: 5
      noise_level: 0.15
      random_seed: 123

  # Initial Validation
  - plugin: "Data Validator"
    config:
      # I/O configuration
      input_data: "data/01_raw/extract_data.csv"
      output_report: "reports/01_extraction_validation.json"

      # Behavior configuration
      required_columns: ["id", "category", "value", "score"]
      min_rows: 1000
      max_null_percentage: 0.05

  # Transform Phase - Clean data
  - plugin: "Data Cleaner"
    config:
      # I/O configuration
      input_data: "data/01_raw/extract_data.csv"
      output_data: "data/02_intermediate/cleaned_data.csv"

      # Behavior configuration
      remove_outliers: true
      outlier_threshold: 3.0
      fill_missing: true
      missing_strategy: "mean"

  # Transform Phase - Feature engineering
  - plugin: "Data Transformer"
    config:
      # I/O configuration
      input_data: "data/02_intermediate/cleaned_data.csv"
      output_data: "data/03_processed/transformed_data.parquet"

      # Behavior configuration
      normalize_columns: ["value", "score"]
      log_transform_columns: ["value"]
      create_derived_features: true

  # Load Phase Validation - Quality check
  - plugin: "Data Quality Checker"
    config:
      # I/O configuration
      input_data: "data/03_processed/transformed_data.parquet"
      output_report: "reports/02_quality_assessment.json"

      # Behavior configuration
      check_duplicates: true
      check_data_types: true
      check_outliers: true
      outlier_threshold: 2.5

# Optional: Override plugin defaults at template level
# (Can be further overridden in case.yaml or via CLI)
# plugins:
#   "Data Generator":
#     random_seed: 42  # Fixed seed for this template
